[project]
name = "mcgpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.9.0",
    "pytest>=9.0.0",
    "ruff>=0.14.4",
    "torch>=2.9.0",
]
